### ISSUE TITLE
Question about the weights of the yolo model

### ISSUE THREAD

**Issue by EbonGit** [fahriwps/GUI-YOLO-pyqt#1]
Hello,
I am working on segmentation of cancerous tissue on mamography images and I would like to be able to easily crop my data around potential masses. When you say to add a pre-trained model, is it the basic model provided with yolo repo or do you have to re-train for the masses in specific?
thx

**Comment by fahriwps** [comment]
> Hello, I am working on segmentation of cancerous tissue on mamography images and I would like to be able to easily crop my data around potential masses. When you say to add a pre-trained model, is it the basic model provided with yolo repo or do you have to re-train for the masses in specific? thx

Hi there, it should be your own re-trained weight for the masses. apologize for providing unclear instruction.
